/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Information to a specific io.miragon.example.base.project
 * @export
 * @interface ProjectTO
 */
export interface ProjectTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectTO
     */
    customer?: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectTO
     */
    address?: any;
}
