### GET project
GET http://localhost:8081/api/project/FlowSquad
Accept: application/json

### Create Project
POST http://localhost:8081/api/project
Content-Type: application/json

{
  "customer": "Muster AG",
  "address": "Musterstraße 123"
}
