version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.19.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    # Debug: command: [nginx-debug, -g, daemon off;]